In [9]:
import pandas as pd

data = {
    'Hours_Studied': [1, 2, 3, 4, 5, 6, 7, 8, 2.5, 3.5, 5.5, 6.5],
    'Attendance': [50, 84, 65, 70, 75, 80, 85, 90, 55, 68, 78, 88],
    'Marks': [100, 98, 95, 90, 94, 98, 99, 100, 93, 92, 100, 100]
} 
df=pd.DataFrame(data)
df

    Hours_Studied  Attendance  Marks
0             1.0          50    100
1             2.0          84     98
2             3.0          65     95
3             4.0          70     90
4             5.0          75     94
5             6.0          80     98
6             7.0          85     99
7             8.0          90    100
8             2.5          55     93
9             3.5          68     92
10            5.5          78    100
11            6.5          88    100

In [17]:
X=df[["Hours_Studied","Attendance"]] #X is the default variable for independent input feature
y=df["Marks"] #y is the default varible for dependent output feature

#multiple Linear regression example

from sklearn.linear_model import LinearRegression
model=LinearRegression()

model.fit(X,y)

model.predict([[2,75]]) #these are the x1,x2 values in y= m1x1 + m2x2 +c (y=mx+c)

C:\Users\SIYA AISH\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([96.48492352])

In [18]:
model.coef_ #slope m

array([0.08318243, 0.10954626])

In [20]:
model.intercept_ #intercept c, 
 #so if you calculcate y=(2*0.0831 + 75*0.10954)+88.1025, you'll get the value of predict i.e 96.484

np.float64(88.10258933960904)

In [21]:
(0.08318243*2)+(0.10954626*75)+88.10258933960904 #the predict value
#so, the error is around 2 because the actual output is 98 and the predicted output is 96.48 something
#so, error is basically the difference of the actual and the predicted output and the least error line will
#be selected as the best fit. 
#And, the predicated value will be near to actual value when you give more features(cols,independent inputs)
#for example, if you give Hours_studied as the only input you might get 95 something, when you use "Attendance"
#too, along with that it'll give around 96, which is called as FEATURE SELECTION, selecting the most important
#feature or the feature which has more impact on the output

96.48492369960904

In [32]:
#simple Linear Regression
X=df[["Hours_Studied"]]
y=df["Marks"]
model1=LinearRegression().fit(X,y)
model1.predict([[2]])

C:\Users\SIYA AISH\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([95.09294872])

In [29]:
model1.coef_

array([0.59615385])

In [30]:
model1.intercept_

np.float64(93.90064102564102)

In [31]:
(0.59615385*2)+93.90064102564102

95.09294872564102

In [35]:
from sklearn.model_selection import train_test_split
#here, it's splitting into 2 sets, training and testing. One, it'll not by heart the pattern ad the other is 
#for evaluating purpose

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
#here, we are giving test size beacuse how much ratio it must split into, it can't be 50 and 50 because ideally
# it needs more for training we either take 70,30 or 80,20. So here, i have taken 80-train and 20-test it's 0.2
X_train

    Hours_Studied
9             3.5
11            6.5
2             3.0
0             1.0
3             4.0
7             8.0
4             5.0
1             2.0
5             6.0

In [37]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
X_train

    Hours_Studied
8             2.5
5             6.0
2             3.0
1             2.0
11            6.5
4             5.0
7             8.0
3             4.0
6             7.0

In [38]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
X_train #see, the order everytime it is run it'll give the different order
#isn't changed beacuse we are giving rando state as 42(42 is a constant)

    Hours_Studied
8             2.5
5             6.0
2             3.0
1             2.0
11            6.5
4             5.0
7             8.0
3             4.0
6             7.0

In [39]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [40]:
model11=LinearRegression().fit(X_train,y_train)
#here, instead of giving whole X and y beacuse the chances of machine memorizing the pattern we are 
#giving only the part of like X_train instaed of X and y_train instead of y
y_pred=model11.predict(X_test)
y_pred
#here, there are 3 output values because of the split and also we are giving X_test as a parameter and it's 
#20% from 0.2 so 3 values, X_train will be 80% so 8 values. Another reason we are actually comparing the test 
#values itself instead of training set as it's done ideally

array([96.9351145 , 94.96564885, 92.50381679])

In [47]:
from sklearn.metrics import mean_squared_error,r2_score, mean_absolute_error
print("error= ", mean_squared_error(y_pred,y_test))
print("R2 score= ", r2_score(y_test,y_pred))
#here in r2 score, y_test afterwards y_pred or it'll give negative value, predicted value to actual not the 
#other way around
print("MAE= ",mean_absolute_error(y_pred,y_test))
#error=(y-y^)difference of the actual output and the predicted output
#also, error=y-(mx+c)

error=  13.021600000000008
R2 score=  0.18614999999999948
MAE=  3.539999999999999

In [44]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,random_state=42)
X_train

    Hours_Studied
0             1.0
8             2.5
5             6.0
2             3.0
1             2.0
11            6.5
4             5.0
7             8.0
3             4.0
6             7.0

In [46]:
model11=LinearRegression().fit(X_train,y_train)
y_pred=model11.predict(X_test)
y_pred
from sklearn.metrics import mean_squared_error,r2_score, mean_absolute_error
print("error= ", mean_squared_error(y_pred,y_test))
print("R2 score= ", r2_score(y_test,y_pred))
print("MAE= ",mean_absolute_error(y_pred,y_test))

error=  13.021600000000008
R2 score=  0.18614999999999948
MAE=  3.539999999999999